
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { CustomTables, CustomFunctions } from './tables';

const SUPABASE_URL = "https://aaqhxeiesnphwhazvkck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcWh4ZWllc25waHdoYXp2a2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Nzc0MzYsImV4cCI6MjA1OTI1MzQzNn0.EnlxhBB2LNxP9GFdx_IkxUMHd5DpnKQlT4wAYfpdknA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Since the Database type doesn't include all tables yet (they're auto-generated),
// we need to create a workaround to make TypeScript happy
type CustomDatabase = Database & {
  public: {
    Tables: Database['public']['Tables'] & CustomTables;
    Functions: Database['public']['Functions'] & CustomFunctions;
  } & Database['public'];
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase.auth.token',
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
