
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaqhxeiesnphwhazvkck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcWh4ZWllc25waHdoYXp2a2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Nzc0MzYsImV4cCI6MjA1OTI1MzQzNn0.EnlxhBB2LNxP9GFdx_IkxUMHd5DpnKQlT4wAYfpdknA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Since the Database type doesn't include the news and application_seasons tables yet (they're auto-generated),
// we need to create a workaround to make TypeScript happy
type CustomDatabase = Database & {
  public: {
    Tables: {
      news: {
        Row: {
          id: string;
          title: string;
          content: string;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          content: string;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          content?: string;
          created_at?: string;
          updated_at?: string | null;
        };
      };
      application_seasons: {
        Row: {
          id: string;
          name: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
        };
      };
    } & Database['public']['Tables'];
  } & Database['public'];
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase.auth.token',
    flowType: 'pkce',
    detectSessionInUrl: true,
    debug: true,
  }
});
